/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package mapackage.server;

import mapackage.common.Common;

public class App {
    public static void main(String[] args) {
        System.out.println(Common.string());
    }
}
